/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Earnings": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Events": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Positions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProcessStock": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PullPrices": {
      "type": "sst.aws.Cron"
    }
    "PullMacd": {
      "type": "sst.aws.Cron"
    }
    "EvaluateAlerts": {
      "type": "sst.aws.Cron"
    }
    "SignalAlerts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MarketPulse": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PullPulse": {
      "type": "sst.aws.Cron"
    }
    "Stocks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
