/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "API_BEARER_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Earnings": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Events": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FMP_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Industries": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MarketAlignment": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MarketPulse": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MarketPulseSnapshot": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MarketRegime": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PULSE_REFRESH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Positions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProcessStock": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PulseEvents": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "RealtimeApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "SignalAlerts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Signals": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "Stocks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Ticks": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "WsConnections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}